//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class AmanpreetPortEntities1 : DbContext
{
    public AmanpreetPortEntities1()
        : base("name=AmanpreetPortEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<BannerInfo> BannerInfoes { get; set; }
    public DbSet<CategoryInfo> CategoryInfoes { get; set; }
    public DbSet<ImageInfo> ImageInfoes { get; set; }
    public DbSet<LoginInfo> LoginInfoes { get; set; }
    public DbSet<videoYoutube> videoYoutubes { get; set; }
}
